#!/bin/bash

# 📋 MENU PRINCIPAL - Gestionnaire WiFi
# Toutes les options disponibles

clear

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  🌐 GESTIONNAIRE WIFI                          ║"
echo "║                     Menu Principal                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "🎯 QUE VOULEZ-VOUS FAIRE ?"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│  🎮 TESTER IMMÉDIATEMENT (30 secondes)                        │"
echo "│     ./demo.sh                                                  │"
echo "│     → Lance l'app en mode démo automatiquement                │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│  🚀 DÉPLOYER POUR PRODUCTION (2-10 minutes)                   │"
echo "│     ./deploy-facile.sh                                         │"
echo "│     → Menu interactif avec 4 options de déploiement           │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

echo "📋 OPTIONS DÉTAILLÉES :"
echo ""
echo "1️⃣  🎮 ./demo.sh"
echo "   ↳ Test instantané sur cet ordinateur"
echo "   ↳ Mode démo intégré (IP: 192.168.1.100)"
echo "   ↳ Port automatique si 5000 occupé"
echo ""
echo "2️⃣  🖥️  ./deploy-facile.sh → Option 1 (Local)"
echo "   ↳ Installation complète en local"
echo "   ↳ Configuration environnement"
echo "   ↳ Tests automatiques"
echo ""
echo "3️⃣  🐳 ./deploy-facile.sh → Option 2 (Docker)"
echo "   ↳ Conteneur Docker automatique"
echo "   ↳ Image optimisée"
echo "   ↳ Démarrage automatique"
echo ""
echo "4️⃣  🌐 ./deploy-facile.sh → Option 3 (Web LWS)"
echo "   ↳ Package prêt pour hébergement mutualisé"
echo "   ↳ Archive .tar.gz automatique"
echo "   ↳ Instructions d'upload incluses"
echo ""
echo "5️⃣  🖥️  ./deploy-facile.sh → Option 4 (VPS LWS)"
echo "   ↳ Script d'installation VPS automatique"
echo "   ↳ Nginx + Gunicorn + SSL"
echo "   ↳ Service systemd inclus"
echo ""

echo "🎮 DONNÉES DE TEST (Mode Démo) :"
echo "   📍 IP Routeur    : 192.168.1.100"
echo "   👤 Utilisateur   : demo"
echo "   🔑 Mot de passe  : demo"
echo ""

echo "📚 DOCUMENTATION DISPONIBLE :"
echo "   📖 README.md              : Guide principal"
echo "   🚀 GUIDE-FACILE.md        : Instructions ultra-simples"
echo "   ⚡ COMMANDES-RAPIDES.md   : Commandes essentielles"
echo "   ✅ DEPLOYMENT_STATUS.md   : Statut de déploiement"
echo ""

read -p "Appuyez sur Entrée pour voir les fichiers disponibles..."

echo ""
echo "📁 FICHIERS DANS LE PROJET :"
ls -la *.sh *.md | grep -E '\.(sh|md)$' | awk '{print "   " $9 " (" $5 " bytes)"}'

echo ""
echo "🎯 RECOMMANDATION :"
echo ""
echo "   👉 Pour tester rapidement    : ./demo.sh"
echo "   👉 Pour déployer facilement  : ./deploy-facile.sh"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           🏆 TOUT EST PRÊT - CHOISISSEZ VOTRE OPTION !         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
